# Generated by Django 5.0.6 on 2024-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attributekey_attributevalue_attributeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('Billing_address', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
